// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ProjetoAEDI.Data;

#nullable disable

namespace ProjetoAEDI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ProjetoAEDI.Models.Adocao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AdotanteId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DataAdocao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("GatinhoId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AdotanteId");

                    b.HasIndex("GatinhoId")
                        .IsUnique();

                    b.ToTable("Adocoes");
                });

            modelBuilder.Entity("ProjetoAEDI.Models.Adotante", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Contato")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("HistoricoVisitas")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Preferencias")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Adotantes");
                });

            modelBuilder.Entity("ProjetoAEDI.Models.Gatinho", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Cor")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("Idade")
                        .HasColumnType("integer");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("RequisitosEspeciais")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Temperamento")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("Gatinhos");
                });

            modelBuilder.Entity("ProjetoAEDI.Models.Adocao", b =>
                {
                    b.HasOne("ProjetoAEDI.Models.Adotante", "Adotante")
                        .WithMany("Adocoes")
                        .HasForeignKey("AdotanteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProjetoAEDI.Models.Gatinho", "Gatinho")
                        .WithOne("Adocao")
                        .HasForeignKey("ProjetoAEDI.Models.Adocao", "GatinhoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Adotante");

                    b.Navigation("Gatinho");
                });

            modelBuilder.Entity("ProjetoAEDI.Models.Adotante", b =>
                {
                    b.Navigation("Adocoes");
                });

            modelBuilder.Entity("ProjetoAEDI.Models.Gatinho", b =>
                {
                    b.Navigation("Adocao")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
